/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.azreco.asr.client;

/**
 *
 * @author toghrul
 */
public enum AudioSource {
    // audio format is one of these formats: .mp4, .wav and etc.
    AS_STANDARD(0),
    // audio input is the realtime stream of 16000 hz samples generated by device microphine
    AS_REALTIME(1);
    
    private int value;
    
    private AudioSource(int value) {    
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }
}
